<?php
/**
 * Tyche theme setup.
 *
 * Tyche is a block theme. The layout lives in templates/*.html and parts/*.html,
 * the design system in theme.json (generated by .dev/build_theme.py) and the
 * sections in patterns/*.php. This file carries only what those cannot express:
 * supports flags, asset enqueues, block styles, pattern categories and icons.
 *
 * Everything here is presentation. Store features that need settings or data --
 * a sticky add-to-cart bar, a free-shipping progress bar, swatches, quick view --
 * belong in a plugin, and the theme styles them when one provides them.
 *
 * @package Tyche
 */

defined( 'ABSPATH' ) || exit;

define( 'TYCHE_VERSION', '2.0.0-dev.11' );

require get_template_directory() . '/inc/setup.php';
require get_template_directory() . '/inc/template-tags.php';
require get_template_directory() . '/inc/block-styles.php';
require get_template_directory() . '/inc/patterns.php';
require get_template_directory() . '/inc/icons.php';
require get_template_directory() . '/inc/woocommerce.php';
require get_template_directory() . '/inc/front-page.php';
require get_template_directory() . '/inc/upgrade.php';
